# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: cc8b3de
_src_path: https://github.com/MeteoSwiss-APN/mch-python-blueprint.git
email: marco.ketzel@hotmail.com
full_name: Marco Ketzel
github_username: MeteoSwiss-APN
module_name: moveroplot
project_doc_url: https://github.io/MeteoSwiss-APN/movero-plot
project_github: https://github.com/MeteoSwiss-APN/movero-plot
project_keywords: movero-plot
project_name: movero-plot
project_short_description: Movero-plot
project_slug: movero-plot
project_ssh_url: git+ssh://git@github.com/MeteoSwiss-APN/movero-plot.git
python_version: '3.10'
version: 0.1.0
year: '2023'
