channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.7.22
  - cartopy=0.21.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - conda=23.5.2
  - conda-content-trust=0.1.3
  - conda-libmamba-solver=23.5.0
  - conda-package-handling=2.1.0
  - conda-package-streaming=0.8.0
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - geos=3.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipdb=0.13.13
  - ipython=8.16.1
  - isort=5.12.0
  - jedi=0.19.1
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libarchive=3.6.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.1.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libmamba=1.4.1
  - libmambapy=1.4.1
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=12.15
  - libsolv=0.7.22
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.11
  - packaging=23.0
  - pandas=2.1.1
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pluggy=1.0.0
  - ply=3.11
  - proj=8.2.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.29.0
  - ruamel.yaml=0.17.21
  - setuptools=67.8.0
  - shapely=2.0.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.11.2
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.8
  - wheel=0.38.4
  - xz=5.4.2
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
